### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by AskYous** [islamic-apps/alquran-web-app#1]
Assalaamu 'Alaikum Wa Rahmatullaahee Wa Baraakatuh,

May Allaah reward you for the work that you've done. It's honestly amazing. I am building a website and I need access to the data in the Qur'aan. To use yours, is there a fee? Do I have to do anything to use the data?

Or can I just download the data and use it on my own? I don't intend to use it for commercial use.

**Comment by meezaan** [comment]
Alaykum Salaam,

Shukran and JazakAllah Khair.

Here is the license: https://github.com/islamic-apps/alquran-web-app/blob/master/LICENSE

You can either use all the data on OneDrive, or you can simply use the API. Either is free.

**Comment by AskYous** [comment]
May Allaah reward you brother.

**Comment by meezaan** [comment]
Shukran brother, and you.

With Prayers,

Meezaan-ud-Din

**Comment by azzamsa** [comment]
I used to have the .sql from the OneDrive link you provided. Now, I can't find the link. Is it taken down?

**Comment by meezaan** [comment]
Yes, that link has indeed been removed. The same SQL file is available in the git repo at https://github.com/islamic-network/api.alquran.cloud. It's not the latest file but it's got all the table structure and a good 80% of the data in it.

**Comment by azzamsa** [comment]
> Yes, that link has indeed been removed. The same SQL file is available in the git repo at https://github.com/islamic-network/api.alquran.cloud. It's not the latest file but it's got all the table structure and a good 80% of the data in it.

Any reason it is 80%?

**Comment by meezaan** [comment]
It's just there for development purposes, so it does not get updated unless there's a structural change to the database. The same was true for the OneDrive file, by the way.

If you are after the data, I can give you one of the backups from the cluster.

**Comment by azzamsa** [comment]
> It's just there for development purposes.

Oh I see.


> If you are after the data, I can give you one of the backups from the cluster.

Very glad to have it. How can I receive it?

**Comment by meezaan** [comment]
> > It's just there for development purposes.
> 
> Oh I see.
> 
> > If you are after the data, I can give you one of the backups from the cluster.
> 
> Very glad to have it. How can I receive it?

@azzamsa https://ap-south-1.linodeobjects.com/islamic-network-backups/alquran/singapore/api/database/2022/Jul/quran-31-Jul-2022.sql.tar.gz.

**Comment by azzamsa** [comment]
@meezaan Huge thanks!
